language: csharp

solution: dotNetRDF.sln

addons:
  sonarcloud:
    organization: "adamtorok96-github" # the key of the org you chose at step #3
    token:
      secure: 66718e96ab8ac15b407d26340fce6df2f3246f8c # encrypted value of your token

matrix:
  include:
    - mono: none
      dotnet: 1.1

      install:
       - dotnet restore
       - dotnet build dotNetRDF.sln
       #- ./build.ps1 -Target Pack --configuration=Release --NuGetVersion=$env:GitVersion_NuGetVersion
         
      script:
        - dotnet test -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
#        - curl -s https://codecov.io/bash > codecov
#        - chmod +x codecov
#        - ./codecov -f "*opencover.xml"
        
      # - sonar-scanner
    
#    - mono: latest
#      
#      install:
#        - nuget restore dotNetRDF.sln
#        #- nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
#        #- msbuild /p:Configuration=Release dotNetRDF.sln
#       # - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
#        #- nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
#          
#      script:
        #- xbuild /p:Configuration=Release dotNetRDF.sln
        #- mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Testing/unittest/bin/Release/netcoreapp2.0/dotNetRDF.Test.dll
        #- mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./Testing/unittest/bin/Release/netcoreapp2.0/dotNetRDF.Test.dll