language: csharp
mono: none
dotnet: 2.0
script:
 - dotnet restore
 addons:
  sonarcloud:
    organization: "krumplipucolo-github" # the key of the org you chose at step #3
    token:
      secure: b601446d564b2d1fdc47c1b5be040f9e5ed7668a # encrypted value of your token
