language: csharp

solution: dotNetRDF.sln

addons:
  sonarcloud:
    organization: "adamtorok96-github" # the key of the org you chose at step #3
    token:
      secure: 66718e96ab8ac15b407d26340fce6df2f3246f8c # encrypted value of your token

matrix:
  include:
    - dotnet: 2.0
      mono: none

      install:
       - dotnet restore
         
      script:
       - dotnet test
       - sonar-scanner
    
    - mono: latest
      
      install:
        - nuget restore dotNetRDF.sln
        - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
          
      script:
        - msbuild /p:Configuration=Release dotNetRDF.sln
        - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./Testing/unittest/bin/Release/netcoreapp2.0/dotNetRDF.Test.dll