language: csharp

solution: dotNetRDF.sln

addons:
  sonarcloud:
    organization: "adamtorok96-github" # the key of the org you chose at step #3
    token:
      secure: 66718e96ab8ac15b407d26340fce6df2f3246f8c # encrypted value of your token

matrix:
  include:
    - mono: none
      dotnet: 1.1

      install:
       - dotnet restore
         
      script:
      # - dotnet test
       - sonar-scanner
    
    - mono: latest
      
      install:
        - nuget restore dotNetRDF.sln
        #- msbuild /p:Configuration=Release dotNetRDF.sln
       # - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
        #- nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
          
      script:
       # - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Testing/unittest/bin/Release/netcoreapp2.0/dotNetRDF.Test.dll
        #- mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./Testing/unittest/bin/Release/netcoreapp2.0/dotNetRDF.Test.dll